/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _courier_new_0_h_
#define _courier_new_0_h_
//---------------------------------------------------------------------------------
extern const unsigned char courier_new_0[];
extern const int courier_new_0_size;
//---------------------------------------------------------------------------------
#endif //_courier_new_0_h_
//---------------------------------------------------------------------------------
