/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _courier_new_h_
#define _courier_new_h_
//---------------------------------------------------------------------------------
extern const unsigned char courier_new[];
extern const int courier_new_size;
//---------------------------------------------------------------------------------
#endif //_courier_new_h_
//---------------------------------------------------------------------------------
