/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _test_triangle_h_
#define _test_triangle_h_
//---------------------------------------------------------------------------------
extern const unsigned char test_triangle[];
extern const int test_triangle_size;
//---------------------------------------------------------------------------------
#endif //_test_triangle_h_
//---------------------------------------------------------------------------------
