/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _vutest_data_h_
#define _vutest_data_h_
//---------------------------------------------------------------------------------
extern const unsigned char vutest_data[];
extern const int vutest_data_size;
//---------------------------------------------------------------------------------
#endif //_vutest_data_h_
//---------------------------------------------------------------------------------
